### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Tuvqlu** [JavierLeon9966/ProperDuels#11]
1. Clashes with PocKit, change kit command to /duelkit 
2. When you reload server, all arenas and kits get deleted
3. 
please fix, I want to play duels

**Comment by JavierLeon9966** [comment]
1. I don’t think that’s my fault. Since the user decides what plugin to use when it overrides something.
2. I submitted the fix, now you would need to wait until the reviewers accept it

**Comment by JavierLeon9966** [comment]
You could also send the error message that the crash dump produced to see if it was really my plugin’s fault

**Comment by Tuvqlu** [comment]
Yeah, I appreciate you for making a fix thanks :D

**Comment by JavierLeon9966** [comment]
You, you can work around the issue by just using `/properduels:kit` for now until I add an alias for it

**Comment by Tuvqlu** [comment]
Thanks! Also, you should add a win reward!
