### ISSUE TITLE
Crash when leaving and letting an invite expire

### ISSUE THREAD

**Issue by logannn61** [JavierLeon9966/ProperDuels#16]
Crashes the server if a player sends a duel invite then leaves and the target accepts the invite of the left player
https://crash.pmmp.io/view/6196665

**Comment by reyyan987** [comment]
> Crashes the server if a player sends a duel invite then leaves and the target accepts the invite of the left player https://crash.pmmp.io/view/6196665

OK Will be looking into it

**Comment by JavierLeon9966** [comment]
Apparently it only happens when it expires
