### ISSUE TITLE
Rename /kit to /duelkit

### ISSUE THREAD

**Issue by Joshiiiii** [JavierLeon9966/ProperDuels#17]
Since there are other kits plugins that use the /kit command, it would be helpful to use the /duelkit instead for the duel kits.
Thanks!
Joshua

**Comment by JavierLeon9966** [comment]
You can already add that alias using the `pocketmine.yml` file in the `aliases` option:
```yaml
duelkit: "properduels:kit $1 $2"
```

**Comment by Joshiiiii** [comment]
Okay, thank you!
