### ISSUE TITLE
my suggestion

### ISSUE THREAD

**Issue by MasnubIndo** [JavierLeon9966/ProperDuels#22]

**Comment by MasnubIndo** [comment]
please add a sumomode, vsbotmode, bowmode, isanemode, overpowermode, gapplemode, nodebuffmode, combomode (in ui form), and scorehud in game

**Comment by JavierLeon9966** [comment]
No, this plugin isn't meant to add every single type of mode into a duels plugin, search a plugin that adds them or that uses this one as an extension

**Comment by MasnubIndo** [comment]
no plugin you mean, please add this like nethergames server🥹

**Comment by JavierLeon9966** [comment]
> Like nethergames
Every server should be unique and this plugin will make all server be unique on their own. If I make it do a specific thing only specific people would want those things for their servers
